window.BUDGET_LANG_EN = {
  tabs: [
    "💰 Budget",
    "📊 Reports",
    "💱 FX Strategy",
    "📈 Inflation History",
    "🔮 Outlook",
    "🏠 Loan Optimization",
    "🛡 Risk Analysis"
  ],
  h3: [
    "Income",
    "Home Loan",
    "Vehicle Financing",
    "Selected loan notes",
    "Detailed Expenses",
    "Budget Analysis",
    "Expense Distribution",
    "Expense distribution comparison",
    "FX sensitivity report",
    "Debt and fixed-load report",
    "12-month overview",
    "Interpretive summary",
    "How much should you convert to TRY?",
    "Monthly conversion strategy by FX scenario",
    "Emergency fund strategy (single income critical)",
    "How exchange-rate changes affect your budget",
    "Annual TurkStat inflation (2020-2026)",
    "USD/TRY history (2020-2026)",
    "TRY value of your income in past years",
    "Loss of purchasing power of TRY 10,000 (2020-2026)",
    "USD/TRY projection 2026-2031",
    "TRY value of your income 2026-2031",
    "Real USD cost of your loan payment 2026-2031",
    "Budget impact when partner income unlocks",
    "Scenario comparison",
    "Total payment comparison",
    "Monthly installment (TRY and USD)",
    "Recommendations for USD earners",
    "Simulator",
    "Live loan comparison - CollectAPI",
    "Risk profile - single-income USD household, Turkey 2026",
    "Stress test - worst cases",
    "Quick Setup"
  ],
  hero: [
    "Plan housing, a car, and monthly life in Turkey in one connected view.",
    "This page links your USD income, TRY expenses, home financing, vehicle financing, and FX scenarios together. For the best result, enter your real income, debt, down payment, and recurring expense numbers; then use the CollectAPI loan comparison section to push selected offers directly back into the main budget."
  ],
  labels: [
    "Monthly USD income",
    "Spouse / second income (USD)",
    "Housing plan",
    "Vehicle plan",
    "Spending style",
    "Household type",
    "Your USD income",
    "Spouse income - current (USD)",
    "Planned spouse income (USD) 🔓",
    "Extra TRY income (rent etc.)",
    "Live USD/TRY rate",
    "Home price (TRY)",
    "Down payment (TRY)",
    "Monthly interest (%)",
    "Term",
    "Balloon payment (TRY)",
    "Vehicle price (TRY)",
    "Down payment (TRY)",
    "Monthly interest (%)",
    "Term",
    "Monthly TRY expenses (including loans)",
    "USD/TRY rate",
    "Monthly USD income",
    "Home price (TRY)",
    "Down payment (TRY)",
    "Monthly interest (%)",
    "Term (months)",
    "USD income",
    "USD/TRY",
    "CollectAPI token",
    "Amount for home offer",
    "Home term (months)",
    "Amount for vehicle offer",
    "Vehicle term (months)",
    "Planned spouse USD income",
    "How many months until it starts?"
  ],
  mlbls: [
    "Monthly TRY income",
    "Total expenses",
    "Net balance",
    "Savings rate",
    "Total income",
    "Total expenses",
    "Monthly net",
    "Debt load",
    "Savings rate",
    "2022 inflation peak",
    "2025 year-end",
    "USD/TRY (2020→2026)"
  ],
  welcomeTitles: [
    "1. Enter income",
    "2. Define the house and car",
    "3. Make expenses realistic",
    "4. Select the API offer",
    "Budget",
    "FX Strategy",
    "Inflation History",
    "Outlook",
    "Loan Optimization",
    "Risk Analysis"
  ],
  welcomeBodies: [
    "In the Budget tab, enter your USD income, spouse income if any, and any extra TRY income. These fields drive all ratios and risk readings.",
    "Use the house and vehicle cards to enter price, down payment, term, and rate assumptions. Monthly installments feed directly into total expenses.",
    "Use the detailed expense section to tune groceries, transport, health, and other recurring costs so the model reflects real life.",
    "In the loan comparison section, you can select a home or vehicle loan offer from CollectAPI and write it back into the main budget.",
    "Main input screen. Income, housing, vehicle finance, and recurring living expenses are connected here.",
    "Shows how much USD needs to be converted and how large your emergency fund should be.",
    "Places today's numbers into historical inflation and exchange-rate context.",
    "Shows how your budget may evolve under different exchange-rate scenarios.",
    "Fetches live loan offers and lets you import selected offers into the main budget.",
    "Tests how resilient your budget is under income shocks, FX drops, and unexpected expenses."
  ],
  welcomeTips: [
    "<b>Note:</b> This warning assumes the household depends mainly on a single USD earner. If FX rises, your TRY income improves; if income is interrupted or a large expense appears, there is no second income buffer. This is why the planner interprets debt-to-income ratios more conservatively, recommends a 9-12 month emergency fund, and centers risk analysis on a single-income scenario.",
    "<b>Who is this for?</b> This section creates a quick starter template for first-time users. It does not change your default values unless the apply button is used."
  ],
  welcomeHelpers: [
    "This template is optional. It creates a starting point and every field remains editable afterward."
  ]
};
